server:
  port: 8080

camel:
  springboot:
    name: ServicesRest
  component:
    servlet:
      mapping:
        contextPath: /camel/*
    rabbitmq:
      hostname: 10.x.x.x
      port-number: 5672
      username: integracion
      password: xxx
    

management:
  port: 8081
  security:
    enabled: false

endpoints:
  enabled: false
  health:
    enabled: true

quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s
